### PR TITLE
Show sample log, a note about ssl and reference bcsandbox

### PR DESCRIPTION
**Pull request by tfenster**
- Add some sample log output so that readers understand what to expect and have confirmation that they are on the right path
- Add a note about SSL warnings as those might confuse users
- Reference

### CODE REVIEW

**Comment by edupont04** [comment]
This PR is aiming for the live branch, which is not allowed. Can we replicate it in the master branch on behalf of Tobias Fenster?

**Comment by edupont04** [comment]
By agreement with Tobias, closing this Pr.

**Comment by edupont04** [comment]
Reopening - sorry for the confusion!

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution, I will implement the fixes in the private repo. Thanks again, much appreciated.

**Comment by SusanneWindfeldPedersen** [comment]
And the topic is now refreshed on live, so closing this PR. Thanks again.

**Pull request closed without merging**
