### PR TITLE
Remove obsolete Transactability notes from Entitlement Docs

### PR DESCRIPTION
**Pull request by tinestaric**
Transactability has been around for a while now, but a couple of pages still contain a note that entitlements are only available for MS apps. 
This PR removes the now obsolete notes from docs.

image

Additionally, the IsEntitled page had a note that it only works OnPrem, which is not true, so I reworded the note to reflect the actual difference between usage of it OnPrem vs Online

### CODE REVIEW

**Comment by tinestaric** [comment]
@microsoft-github-policy-service agree

**Comment by tinestaric** [comment]
@KennieNP This is one of the PRs I mentioned during the Q&A. How could I pull in for the topic of entitlements and transactability?
I have a couple of other updates for this area that I ended up packaging in a blog post but would be better off as part of the docs. 
https://tine.staric.net/blog/2024/transactability-entitlements/

**Comment by tinestaric** [comment]
@ agree

**Comment by SusanneWindfeldPedersen** [comment]
Hello @tinestaric - thanks for your PR, I'll take it in, but need to leave out the auto-generated method, because we have to handle that in source code here - if you want to update the PR yourself, you need to remove the https://github.com/tinestaric/dynamics365smb-devitpro-pb/blob/RemoveObsoleteEntitlementNotes/dev-itpro/developer/methods-auto/navapp/navapp-isentitled-method.md article from this PR. Then we'll make a push on the auto-gen once it's fixed too. Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution, we'll close this PR and fix this in our private repo and then push live. Thanks again!

**Pull request closed without merging**
