### PR TITLE
Update document on runtime packages to state that the version of the target platform must be the same as the version of the platform where they are produced.

### PR DESCRIPTION
**Pull request by atoader**

### CODE REVIEW

**Comment by Addice73** [comment]
This is a very very bad news

**Comment by atoader** [comment]
@Addice73 could you elaborate?

**Comment by demiliani** [comment]
Does that mean that a package created on version 16.5 can be deployed ONLY on version 16.5 (otherwise error thrown) or that it COULD have problems on certain situations?

**Comment by eric-silverw-com** [comment]
Ok everyone, take a deep breath and relax.  If you follow the link on this, you'll see that this is just a documentation update. 

Specifically, it states: "Runtime packages are guaranteed to work only if published to a platform with the same version as the one where they were produced." 

If you think about it, this should be pretty obvious.  If you deploy a **runtime** on a platform that has a different version from the one it was created on, all bets are off.  The reason being that runtime versions aren't recompiled on installation so any problems that might occur won't be found until you run them.  Normally, when you deploy on a Docker or Cloud environment your extensions are compiled on install and if there are any problems it rejects them.  This is why the version doesn't matter so much there.

**Comment by Addice73** [comment]
PRECONDITION
1 Runtime packages are designed for in prem only 
2 Ms warmly suggest to extend and not customize base app.
3 to extend the base app we often need new events that are included in new cu.
4 on prem customer does not pay for monthly updates that are not tailored to their needs.
5 on prem environment are distributed and cannot be updated massively  through scripting.
6 as ISV we need to deploy new apps and changes to all customer 
7 run time packages compatibility may break (we don't know if it happens) monthly
8 as an ISV we have more than 100 runtime pkg

CONSEQUENCES
1 as an ISV when we fix or change app we need to rebuild it on all available cu to ensure that customer tha rely on different update level can install it. Even if the changes are trivial and version indipendent. Then publish the new ock for every version. 

2 We run automatic builds on 34 localisation with dockers and test code units. This take a lot of time and resources to run. (when running smooth) 

3 to deliver a quick fix to one customer we need to develop, test it and deploy it to its precise version. That means that we need environments and test dataset for each cu. 

CONCLUSION
1 a lifetime expectation of 30 days for an app is definitely incompatible with onprem business

2 rebuilding and running different packages version for each cu is completely unsustainable for a typical bc partner 
3 technically you are right telling that is pretty obvious that can works only on same version. But you forget that time to market and business aspect should be preconditions and not consequences of technical choices. 
In other word if is correct to keep compatibility for the same versions that should work indipentently of the number of time variable. Releasing cu monthly or daily does not change the technical perspective but from a business point of view this is simply wrong. 

From a customer perspective when I buy a product I'm expecting a free guarentee for a reasonable period of time (EU says 12 or 24 months). Since upgrades are not free for onprem you should consider a reasonable period of time in which partners and resellers can release and install updates and fixes with reasonable low cost. Run time packages should be compatible for a minimum of six months or a reasonable 12 months period. 
Run time packages are made for onprem businesses. On premises business has is rules and times that should be respected. 
Saas is not affected at all by this problem, I can confirm it since we have 45 apps on apsource and none of that problems

**Comment by eric-silverw-com** [comment]
I'm not claiming to be an expert here but as far as I can tell, nobody's saying that the cloud version is guaranteed to work either.  It's just that when an install or upgrade happens in the cloud, the extension is recompiled and if there are problems it gets rejected.  You may be able to simulate this with the on-prem installations by running the repair-navapp command against your apps after an upgrade.  I tried it on one of our on-prem installs and it seemed to work.  The documentation for this command says that it recompiles the app agains the current base.  It also says that it should be run any time the base has changed so maybe it was intended for just this situation.

https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/repair-navapp?view=businesscentral-ps-16#:~:text=%5B%5D-,Description,for%20completing%20the%20publishing%20process.

**Comment by Addice73** [comment]
Repair NAV app used in combination with runtime package and nodebug options broken** several databases during our testing and (also in production environment). I think is designed to work when source are accessible to the framework.
Ip protection is possible only with this two options togheter.

**Definition of broken :cannot remove or install extension, restarting the service fail because application metadata are inconsistent. Need to put current dB in recicled bin and restart from a bak file or perform sql updates and delete to remove broken data.

Andrea

________________________________

**Comment by pranav4186** [comment]
I have been there Repair-NAVApp produced metadata error during upgrading minor version, could not restart service I even tried to copy metadata of that object from working database through sql but it did not work and I had to start over. 
In next round Repair-NAVApp worked and finally finished the upgrade, so looks like it does recompile the app against its dependency but yes I cross my fingers every time I run it.
So if MS ask us to match minor version between production and development then it would be helpful if they fix Repair-NAVApp and give some user friendly error message!

**Comment by erolkunman** [comment]
After doing multiple OnPrem upgrades (both CU upgrades on BC15,BC16 and also bigger upgrade BC15->BC16) I can confirm, that we cannot use runtime apps anymore, since they do not work after the upgrade.
Although system shows they are installed, user cannot find them with tell me or they get metadata error.

The solution is to increase the apps version nr. and package it, then Publist, Sync and Start-NAVAppDataUpgrade.
But if customer uses apps from other providers then us, then we don't have the code and cannot fix app.

We like runtime apps, because they help to protect our intellectual property but we cannot use them because then basically customer cannot upgrade their Business Central.

That's not ok.

[https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1435](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/1435)

**Comment by SusanneWindfeldPedersen** [comment]
This documentation PR is outdated, hence it is being recreated in our private repo and then pushed live. Thanks.

**Pull request closed without merging**
