### PR TITLE
Update time-data-type.md

### PR DESCRIPTION
**Pull request by NKarolak**
Based on Nikola Kukrika's input on https://www.yammer.com/dynamicsnavdev/threads/2506817338753024, I've added a section on how to compare time values without their milliseconds portion. Once this PR is fixed and approved, I'd add a similar section to the DateTime data type article as well.

@SusanneWindfeldPedersen Please check all URLs I've added, as I have no possibility to test them in the preview.

### CODE REVIEW

**Comment by lvanvugt** [comment]
> Based on Nikola Kukrika's input on https://www.yammer.com/dynamicsnavdev/threads/2506817338753024, I've added a section on how to compare time values without their milliseconds portion. Once this PR is fixed and approved, I'd add a similar section to the DateTime data type article as well.

Approved by me.

**Comment by lvlaanderen** [comment]
I personally would change the case statement to this:
case true of
        TimeA = TimeB, Abs(TimeA - TimeB) < 10:
            exit(0);
        TimeA = 0T:
            exit(-1);
        TimeB = 0T, TimeA > TimeB:
            exit(1);
        else
            exit(-1);
    end;
    
This way every exit value is only present once, except for the final else of course

**Comment by NKarolak** [comment]
@lvlaanderen But this way, 0 would be returned if TimeA and TimeB are both empty.

**Comment by JohnnyUndercover** [comment]
> I personally would change the case statement to this:
> case true of
>         TimeA = TimeB, Abs(TimeA - TimeB) < 10:
>             exit(0);
>         TimeA = 0T:
>             exit(-1);
>         TimeB = 0T, TimeA > TimeB:
>             exit(1);
>         else
>             exit(-1);
>     end;
>     
> This way every exit value is only present once, except for the final else of course 

I do not agree. In my opinion the readability and debuggability of separated cases is better.

**Comment by lvlaanderen** [comment]
> @lvlaanderen But this way, 0 will be returned if TimeA and TimeB are both empty.

This will still be the case in your version, I didn't change the options but just moved them around
To avoid that you would need a (TimeA = 0T and TimeA = TimeB) or (TimeA = 0T and TimeB = 0T) in your case statement

**Comment by NKarolak** [comment]
> > @lvlaanderen But this way, 0 will be returned if TimeA and TimeB are both empty.
> 
> This will still be the case in your version, I didn't change the options but just moved them around To avoid that you would need a (TimeA = 0T and TimeA = TimeB) or (TimeA = 0T and TimeB = 0T) in your case statement

Oops, you are right. This function was a copy from [this standard one](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/651cbe191995f0164639d6562783fafe5d614cf6/BaseApp/Source/Base%20Application/System/Utilities/TypeHelper.Codeunit.al#L161), and I remembered it incorrectly; I thought it handled two empty values differently.

I agree with @JohnnyUndercover that for debugging purposes, it is better to keep the values separate. Additionally, I want to keep it the same as in the standard. Talking about the standard: if you want to have that changed in standard code (not Docs example code), add your thoughts here: https://github.com/microsoft/BusinessCentralApps/issues/483.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your contribution, much appreciated!

**Pull request merged**
